"""Support for bemfa service."""
from __future__ import annotations

import logging
import json
from abc import ABC, abstractmethod
from collections.abc import Mapping, Callable
import hashlib
from typing import Any
import voluptuous as vol
from homeassistant.const import ATTR_ENTITY_ID, STATE_UNAVAILABLE, STATE_UNKNOWN
from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry
from homeassistant.util.decorator import Registry
from homeassistant.util.read_only_dict import ReadOnlyDict

from .const import (
    MSG_OFF,
    MSG_ON,
    MSG_SEPARATOR,
    OPTIONS_FAN_SPEED_0_VALUE,
    OPTIONS_FAN_SPEED_1_VALUE,
    OPTIONS_FAN_SPEED_2_VALUE,
    OPTIONS_FAN_SPEED_3_VALUE,
    OPTIONS_FAN_SPEED_4_VALUE,
    OPTIONS_FAN_SPEED_5_VALUE,
    OPTIONS_FAN_SPEED_7_VALUE,
    OPTIONS_FAN_SPEED_8_VALUE,
    OPTIONS_FAN_SPEED_9_VALUE,
    OPTIONS_NAME,
    TOPIC_PREFIX,
    TopicSuffix,
)

_LOGGING = logging.getLogger(__name__)
UNPUBLISHABLE_STATES = {STATE_UNAVAILABLE, STATE_UNKNOWN}


class Sync(ABC):
    """An abstract class for bemfa syncs."""

    @staticmethod
    @abstractmethod
    def get_config_step_id() -> str:
        """StepId for options flow while config this kind of sync."""
        raise NotImplementedError

    @staticmethod
    @abstractmethod
    def _get_topic_suffix() -> TopicSuffix:
        raise NotImplementedError

    @classmethod
    @abstractmethod
    def collect_supported_syncs(cls, hass: HomeAssistant):
        """Collect all supported bemfa syncs from hass."""
        raise NotImplementedError

    def __init__(
        self,
        hass: HomeAssistant,
        entity_id: str,
        name: str,
    ) -> None:
        """Initialize."""
        self._hass = hass
        self._entity_id = entity_id
        self._name = name
        self._topic = None
        self._config = {}

    @property
    def entity_id(self) -> str:
        """Entity id in hass."""
        return self._entity_id

    @property
    def name(self) -> str:
        """Name in bemfa service."""
        return self._name

    @name.setter
    def name(self, name: str):
        self._name = name

    @property
    def config(self) -> dict[str, str]:
        """User config stored in integration options."""
        return self._config

    @config.setter
    def config(self, config: dict[str, str]):
        self._config = config

    @property
    def topic(self) -> str:
        """Get bemfa topic generated by a stable hass registry id.
        Bemfa service communicates with devices by topic messages.
        Each device corresponds to a particular topic whose suffix is a 3 digit number to indicate its type.
        """
        if self._topic is None:
            # Bemfa topic supports alphanumeric only. Keep the hash short so
            # generated topics are easy to inspect while retaining a stable suffix.
            self._topic = (
                TOPIC_PREFIX
                + hashlib.md5(self._topic_stable_id().encode("utf-8")).hexdigest()[:12]
                + self._get_topic_suffix()
            )
        return self._topic

    def _topic_stable_id(self) -> str:
        """Return a stable source id for topic generation."""

        entry = entity_registry.async_get(self._hass).async_get(self._entity_id)
        if entry is None:
            return self._entity_id

        if entry.unique_id:
            platform = getattr(entry, "platform", "")
            return f"{entry.domain}:{platform}:{entry.unique_id}"

        entry_id = getattr(entry, "id", "")
        if entry_id:
            return f"{entry.domain}:{entry_id}"

        return self._entity_id

    def generate_option_label(self) -> str:
        """Generate label in front end options list as "[domain]name"."""
        domain = self._entity_id.split(".")[0]
        return "[{domain}] {name}".format(domain=domain, name=self._name)

    def generate_details_schema(self) -> dict[str, Any]:
        """Generate schema in front end details setting form."""
        return {vol.Required(OPTIONS_NAME, default=self._name): str}

    @abstractmethod
    def get_watched_entity_ids(self) -> list[str]:
        """When state of one of these entities changes, publish a Bemfa message."""
        raise NotImplementedError

    def should_auto_create(self) -> bool:
        """Return if this sync should be created automatically on startup."""

        return True

    def generate_msg(self) -> dict[str, Any]:
        """Generate a message to send to Bemfa service."""
        payload = self._generate_msg_payload()
        if not payload:
            return {}
        return payload

    def generate_feedback_msg(self, control_msg: Any) -> dict[str, Any]:
        """Generate a full feedback message after a Bemfa control command."""

        control_payload = self._parse_json_payload(control_msg)
        suffix = self._get_topic_suffix()
        payload = self.generate_msg()
        if control_payload is None:
            return payload

        if suffix in (TopicSuffix.CLIMATE, TopicSuffix.THERMOSTAT):
            for key in ("on", "mode", "t", "fan"):
                if key in control_payload:
                    payload[key] = control_payload[key]
            if "v" in control_payload and "fan" not in control_payload:
                payload["fan"] = control_payload["v"]
        return payload

    @staticmethod
    def _parse_json_payload(msg: Any) -> dict[str, Any] | None:
        if isinstance(msg, dict):
            return msg
        try:
            payload = json.loads(msg)
        except (TypeError, ValueError):
            return None
        return payload if isinstance(payload, dict) else None

    def _generate_msg_payload(self) -> dict[str, Any]:
        """Generate a Bemfa MI JSON message payload."""

        parts = self._generate_msg_parts()

        # remove useless tail parts
        while len(parts) > 0 and parts[len(parts) - 1] == "":
            parts.pop()

        return self._parts_to_payload(parts)

    def _parts_to_payload(self, parts: list[Any]) -> dict[str, Any]:
        if not parts:
            return {}

        suffix = self._get_topic_suffix()
        on = parts[0] == MSG_ON
        if suffix in (
            TopicSuffix.OUTLET,
            TopicSuffix.SWITCH,
            TopicSuffix.LIGHT,
            TopicSuffix.FAN,
            TopicSuffix.TV,
            TopicSuffix.AIR_PURIFIER,
        ):
            payload: dict[str, Any] = {"on": on}
            if suffix == TopicSuffix.FAN and len(parts) > 1 and parts[1] != "":
                payload["v"] = _to_int(parts[1])
            if suffix == TopicSuffix.AIR_PURIFIER and len(parts) > 1 and parts[1] != "":
                payload["mode"] = parts[1]
            return payload

        if suffix == TopicSuffix.COVER:
            payload = {"on": on}
            if len(parts) > 1 and parts[1] != "":
                payload["v"] = _to_int(parts[1])
            return payload

        if suffix in (
            TopicSuffix.CLIMATE,
            TopicSuffix.THERMOSTAT,
            TopicSuffix.WATER_HEATER,
        ):
            payload = {"on": on}
            if len(parts) > 1 and parts[1] != "":
                if suffix == TopicSuffix.WATER_HEATER:
                    payload["t"] = _to_int(parts[1])
                else:
                    payload["mode"] = _to_int(parts[1])
            if len(parts) > 2 and parts[2] != "":
                if suffix == TopicSuffix.WATER_HEATER:
                    payload["mode"] = parts[2]
                else:
                    payload["t"] = _to_int(parts[2])
            if suffix != TopicSuffix.WATER_HEATER and len(parts) > 3 and parts[3] != "":
                payload["fan"] = _to_int(parts[3])
            return payload

        if suffix == TopicSuffix.SENSOR:
            return {"on": on}

        return {"on": on}

    @abstractmethod
    def _generate_msg_parts(self) -> list[str]:
        raise NotImplementedError


SYNC_TYPES: Registry[str, type[Sync]] = Registry()


class ControllableSync(Sync):
    """An abstract class for controllable bemfa sync."""

    @staticmethod
    @abstractmethod
    def _supported_domain() -> str | list[str]:
        """Hass domain(s) from which we collect syncs."""
        raise NotImplementedError

    @classmethod
    def collect_supported_syncs(cls, hass: HomeAssistant):
        return [
            cls(hass, state.entity_id, state.name)
            for state in hass.states.async_all(cls._supported_domain())
        ]

    def get_watched_entity_ids(self) -> list[str]:
        return [self._entity_id]

    def _generate_msg_parts(self) -> list[str]:
        state = self._hass.states.get(self._entity_id)
        if state is None or state.state in UNPUBLISHABLE_STATES:
            return []

        generators = self._msg_generators()
        msg = [generators[0](state.state, state.attributes)]

        # if first one is off, the following parts is useless
        if msg[0] != MSG_OFF:
            msg += list(
                map(
                    lambda f: str(f(state.state, state.attributes)),
                    generators[1:],
                )
            )
        return msg

    @abstractmethod
    def _msg_generators(
        self,
    ) -> list[Callable[[str, ReadOnlyDict[Mapping[str, Any]]], str | int]]:
        raise NotImplementedError

    def resolve_msg(self, msg: Any):
        """Resolve a message received from Bemfa service."""
        state = self._hass.states.get(self._entity_id)
        if state is None:
            return

        if self._resolve_json_msg(msg, state.attributes):
            return

        msg_list = self._msg_to_parts(msg, state.attributes)
        if msg_list[0] == MSG_OFF:
            msg_list = [MSG_OFF]  # discard any data followed by "off"

        # generate msg from entity to compare to received msg
        state_msg_list = MSG_SEPARATOR.join(self._generate_msg_parts()).split(
            MSG_SEPARATOR
        )

        for resolver in self._msg_resolvers():
            start_index = resolver[0]
            end_index = min(resolver[1], len(msg_list), len(state_msg_list))
            if msg_list[start_index:end_index] != state_msg_list[start_index:end_index]:
                (domain, service, data) = resolver[2](
                    [_coerce_msg_value(msg) for msg in msg_list[start_index:end_index]],
                    state.attributes,
                )
                data.update({ATTR_ENTITY_ID: self._entity_id})
                self._hass.async_create_task(
                    self._hass.services.async_call(
                        domain=domain,
                        service=service,
                        service_data=data,
                        blocking=False,
                    )
                )
                break  # call only one service at most on each msg received

    def _resolve_json_msg(
        self, msg: Any, attributes: ReadOnlyDict[Mapping[str, Any]]
    ) -> bool:
        if isinstance(msg, dict):
            payload = msg
        else:
            try:
                payload = json.loads(msg)
            except (TypeError, ValueError):
                return False

        if not isinstance(payload, dict):
            return False

        suffix = self._get_topic_suffix()
        if suffix in (TopicSuffix.OUTLET, TopicSuffix.SWITCH, TopicSuffix.TV):
            parts = [MSG_ON if payload.get("on", True) else MSG_OFF]
            (domain, service, data) = self._msg_resolvers()[0][2](parts, attributes)
            self._async_call_service(domain, service, data)
            return True

        if suffix == TopicSuffix.LIGHT:
            from homeassistant.components.light import (
                ATTR_BRIGHTNESS_PCT,
                ATTR_COLOR_TEMP_KELVIN,
                ATTR_RGB_COLOR,
                DOMAIN,
            )
            from homeassistant.const import SERVICE_TURN_OFF, SERVICE_TURN_ON

            if payload.get("on", True) is False:
                self._async_call_service(DOMAIN, SERVICE_TURN_OFF, {})
                return True
            data: dict[str, Any] = {}
            if "bri" in payload:
                data[ATTR_BRIGHTNESS_PCT] = _to_int(payload["bri"])
            if "tv" in payload:
                data[ATTR_COLOR_TEMP_KELVIN] = _to_int(payload["tv"])
            if all(key in payload for key in ("r", "g", "b")):
                data[ATTR_RGB_COLOR] = [
                    _to_int(payload["r"]),
                    _to_int(payload["g"]),
                    _to_int(payload["b"]),
                ]
            self._async_call_service(DOMAIN, SERVICE_TURN_ON, data)
            return True

        if suffix == TopicSuffix.FAN:
            from homeassistant.components.fan import (
                ATTR_PERCENTAGE,
                ATTR_PERCENTAGE_STEP,
                DOMAIN,
                SERVICE_SET_PERCENTAGE,
            )
            from homeassistant.const import SERVICE_TURN_OFF, SERVICE_TURN_ON

            if payload.get("on", True) is False:
                self._async_call_service(DOMAIN, SERVICE_TURN_OFF, {})
                return True
            if "v" in payload and ATTR_PERCENTAGE_STEP in attributes:
                percentage = min(max(_to_int(payload["v"]), 1) * attributes[ATTR_PERCENTAGE_STEP], 100)
                self._async_call_service(
                    DOMAIN, SERVICE_SET_PERCENTAGE, {ATTR_PERCENTAGE: percentage}
                )
                return True
            self._async_call_service(DOMAIN, SERVICE_TURN_ON, {})
            return True

        if suffix == TopicSuffix.COVER:
            from homeassistant.components.cover import ATTR_POSITION, DOMAIN
            from homeassistant.const import (
                SERVICE_CLOSE_COVER,
                SERVICE_OPEN_COVER,
                SERVICE_SET_COVER_POSITION,
            )

            if "v" in payload:
                self._async_call_service(
                    DOMAIN, SERVICE_SET_COVER_POSITION, {ATTR_POSITION: _to_int(payload["v"])}
                )
            else:
                self._async_call_service(
                    DOMAIN,
                    SERVICE_OPEN_COVER if payload.get("on", True) else SERVICE_CLOSE_COVER,
                    {},
                )
            return True

        if suffix in (TopicSuffix.CLIMATE, TopicSuffix.THERMOSTAT):
            from homeassistant.components.climate import (
                ATTR_FAN_MODES,
                ATTR_HVAC_MODE,
                ATTR_PRESET_MODES,
                DOMAIN,
                SERVICE_SET_FAN_MODE,
                SERVICE_SET_HVAC_MODE,
                SERVICE_SET_PRESET_MODE,
                SERVICE_SET_TEMPERATURE,
            )
            from homeassistant.const import ATTR_TEMPERATURE, SERVICE_TURN_OFF, SERVICE_TURN_ON

            if payload.get("on", True) is False:
                self._async_call_service(DOMAIN, SERVICE_TURN_OFF, {})
                return True
            if payload.get("on") is True:
                self._async_call_service(DOMAIN, SERVICE_TURN_ON, {})
            if "mode" in payload:
                mode = _to_int(payload["mode"])
                hvac_mode = _climate_hvac_mode(mode)
                if hvac_mode is not None:
                    self._async_call_service(
                        DOMAIN,
                        SERVICE_SET_HVAC_MODE,
                        {ATTR_HVAC_MODE: hvac_mode},
                    )
                elif preset_mode := _climate_preset_mode(
                    mode, attributes.get(ATTR_PRESET_MODES, [])
                ):
                    self._async_call_service(
                        DOMAIN,
                        SERVICE_SET_PRESET_MODE,
                        {"preset_mode": preset_mode},
                    )
            if "t" in payload:
                self._async_call_service(
                    DOMAIN, SERVICE_SET_TEMPERATURE, {ATTR_TEMPERATURE: _to_int(payload["t"])}
                )
            if "fan" in payload or "v" in payload:
                fan_value = payload.get("fan", payload.get("v"))
                fan_mode = _climate_fan_mode(
                    _to_int(fan_value),
                    self._config,
                    attributes.get(ATTR_FAN_MODES, []),
                )
                if fan_mode is not None:
                    self._async_call_service(
                        DOMAIN,
                        SERVICE_SET_FAN_MODE,
                        {"fan_mode": fan_mode},
                    )
            return True

        if suffix == TopicSuffix.WATER_HEATER:
            from homeassistant.components.water_heater import (
                ATTR_OPERATION_MODE,
                DOMAIN,
                SERVICE_SET_OPERATION_MODE,
                SERVICE_SET_TEMPERATURE,
            )
            from homeassistant.const import ATTR_TEMPERATURE, SERVICE_TURN_OFF, SERVICE_TURN_ON

            if payload.get("on", True) is False:
                self._async_call_service(DOMAIN, SERVICE_TURN_OFF, {})
                return True
            if "on" in payload and len(payload) == 1:
                self._async_call_service(DOMAIN, SERVICE_TURN_ON, {})
            if "t" in payload:
                self._async_call_service(
                    DOMAIN, SERVICE_SET_TEMPERATURE, {ATTR_TEMPERATURE: _to_int(payload["t"])}
                )
            if "mode" in payload:
                self._async_call_service(
                    DOMAIN, SERVICE_SET_OPERATION_MODE, {ATTR_OPERATION_MODE: str(payload["mode"])}
                )
            return True

        if suffix == TopicSuffix.AIR_PURIFIER:
            from homeassistant.components.fan import (
                DOMAIN,
                SERVICE_SET_PRESET_MODE,
            )
            from homeassistant.const import SERVICE_TURN_OFF, SERVICE_TURN_ON

            if payload.get("on", True) is False:
                self._async_call_service(DOMAIN, SERVICE_TURN_OFF, {})
                return True
            if "mode" in payload:
                self._async_call_service(
                    DOMAIN, SERVICE_SET_PRESET_MODE, {"preset_mode": str(payload["mode"])}
                )
                return True
            self._async_call_service(DOMAIN, SERVICE_TURN_ON, {})
            return True

        return False

    def _async_call_service(
        self, domain: str, service: str, data: dict[str, Any]
    ) -> None:
        data.update({ATTR_ENTITY_ID: self._entity_id})
        self._hass.async_create_task(
            self._hass.services.async_call(
                domain=domain,
                service=service,
                service_data=data,
                blocking=False,
            )
        )

    def _msg_to_parts(
        self, msg: Any, attributes: ReadOnlyDict[Mapping[str, Any]]
    ) -> list[str | int]:
        """Convert Bemfa MI JSON into the legacy resolver parts."""

        if isinstance(msg, dict):
            payload = msg
        else:
            try:
                payload = json.loads(msg)
            except (TypeError, ValueError):
                return str(msg).split(MSG_SEPARATOR)

        if not isinstance(payload, dict):
            return [str(payload)]

        suffix = self._get_topic_suffix()
        on = MSG_ON if payload.get("on", True) else MSG_OFF
        parts: list[str | int] = [on]

        if suffix == TopicSuffix.LIGHT:
            if "bri" in payload:
                parts.append(_to_int(payload["bri"]))
            if "tv" in payload:
                parts.append(1000000 // max(_to_int(payload["tv"]), 1))
            elif all(key in payload for key in ("r", "g", "b")):
                parts.append(
                    _to_int(payload["r"]) * 256 * 256
                    + _to_int(payload["g"]) * 256
                    + _to_int(payload["b"])
                )
        elif suffix in (TopicSuffix.FAN, TopicSuffix.COVER):
            if "v" in payload:
                parts.append(_to_int(payload["v"]))
        elif suffix in (TopicSuffix.CLIMATE, TopicSuffix.THERMOSTAT):
            if "mode" in payload:
                parts.append(_to_int(payload["mode"]))
            if "t" in payload:
                while len(parts) < 2:
                    parts.append("")
                parts.append(_to_int(payload["t"]))
            if "fan" in payload or "v" in payload:
                while len(parts) < 3:
                    parts.append("")
                parts.append(_to_int(payload.get("fan", payload.get("v"))))
        elif suffix == TopicSuffix.WATER_HEATER:
            if "t" in payload:
                parts.append(_to_int(payload["t"]))
            if "mode" in payload:
                while len(parts) < 2:
                    parts.append("")
                parts.append(str(payload["mode"]))
        elif suffix == TopicSuffix.AIR_PURIFIER:
            if "mode" in payload:
                parts.append(str(payload["mode"]))

        return parts

    @abstractmethod
    def _msg_resolvers(
        self,
    ) -> list[
        (
            int,
            int,
            Callable[
                [list[str | int], ReadOnlyDict[Mapping[str, Any]]],
                (str, str, dict[str, Any]),
            ],
        )
    ]:
        raise NotImplementedError


def _to_int(value: Any) -> int:
    """Convert JSON scalar values to int for Bemfa payload fields."""

    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return round(value)
    return int(str(value))


def _coerce_msg_value(value: Any) -> str | int:
    if isinstance(value, int):
        return value
    if isinstance(value, str) and value.isdigit():
        return int(value)
    return value


def _climate_supported_modes() -> list[Any]:
    from homeassistant.components.climate import HVACMode

    return [
        HVACMode.AUTO,
        HVACMode.COOL,
        HVACMode.HEAT,
        HVACMode.FAN_ONLY,
        HVACMode.DRY,
    ]


def _climate_hvac_mode(mode: int) -> Any | None:
    modes = _climate_supported_modes()
    if 1 <= mode <= len(modes):
        return modes[mode - 1]
    return None


def _climate_preset_mode(mode: int, preset_modes: list[str]) -> str | None:
    preset_names = {
        6: ("sleep", "Sleep", "sleep_mode", "睡眠"),
        7: ("eco", "Eco", "energy_saving", "节能"),
    }.get(mode, ())
    preset_modes_by_lower = {str(item).lower(): item for item in preset_modes}
    for preset_name in preset_names:
        if preset_name.lower() in preset_modes_by_lower:
            return preset_modes_by_lower[preset_name.lower()]
    return None


def _climate_fan_mode(
    speed: int, sync_config: dict[str, str], fan_modes: list[str]
) -> str | None:
    speed_to_config_key = {
        0: OPTIONS_FAN_SPEED_0_VALUE,
        1: OPTIONS_FAN_SPEED_1_VALUE,
        2: OPTIONS_FAN_SPEED_2_VALUE,
        3: OPTIONS_FAN_SPEED_3_VALUE,
        4: OPTIONS_FAN_SPEED_4_VALUE,
        5: OPTIONS_FAN_SPEED_5_VALUE,
        7: OPTIONS_FAN_SPEED_7_VALUE,
        8: OPTIONS_FAN_SPEED_8_VALUE,
        9: OPTIONS_FAN_SPEED_9_VALUE,
    }
    key = speed_to_config_key.get(speed)
    if key is None:
        return None
    if key in sync_config:
        return sync_config[key]

    if not fan_modes:
        return None
    if speed == 0:
        return _first_matching_mode(fan_modes, ("auto", "自动"))
    if speed == 7:
        return _first_matching_mode(fan_modes, ("low", "低", "低风", "一档"))
    if speed == 8:
        return _first_matching_mode(fan_modes, ("medium", "med", "mid", "中", "中风", "二档"))
    if speed == 9:
        return _first_matching_mode(fan_modes, ("high", "高", "高风", "三档"))

    index = min(speed - 1, len(fan_modes) - 1)
    return fan_modes[index]


def _first_matching_mode(modes: list[str], names: tuple[str, ...]) -> str | None:
    modes_by_lower = {str(item).lower(): item for item in modes}
    for name in names:
        if name.lower() in modes_by_lower:
            return modes_by_lower[name.lower()]
    return None
